version: '2'
services:
  users-service:
    build: ./rest
    ports:
     - "8080:8080"
    depends_on:
     - mysql
  mysql:
    build: ./database
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlpw
  user-interface:
    build: ./src/
    ports:
      - "3001:3001"
      - "3000:3000"